; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.3
	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.3/esp32-arduino-libs-3.0.3.zip
board = esp32dev
monitor_speed = 115200
framework = arduino
lib_deps = 
	https://github.com/simplefoc/Arduino-FOC.git#dev
	chris--a/Keypad@^3.1.1
	bblanchon/ArduinoJson@^7.4.2
	mathertel/RotaryEncoder@^1.5.3
lib_archive = false
build_flags = -I .pio/libdeps/esp32dev/Arduino-FOC/src -I .pio/libdeps/esp32dev/Arduino-FOC/src/communication
extra_scripts = post:upload_fs.py ; Upload SPIFFS after uploading firmware

